<?php declare(strict_types=1);

use Ifuel\EmailBanner\Block\EmailBanner;
use Ifuel\EmailBanner\ViewModel\Config;

/** @var EmailBanner $block */
$viewModel = $block->getViewModel();

/** @var Config $viewModel */
?>

<div id="subscribe-new-popup" class="subscribe-new-container">
    <form id="newsletter-header-subscribe" class="newsletter-content">
        <?= $block->getChildHtml('email.banner.content'); ?>
        <input name="email" id="cm_email" onfocus="if(this.value=='Enter Your Email') this.value=''" onblur="if(this.value=='') this.value='Enter Your Email'" class="validate-email required-entry field-left" type="text" value="Enter Your Email" />
        <button type="submit" class="button">Sign Me Up</button>
    </form>
    <div class="newsletter-message"></div>
    <div class="tester"></div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "Ifuel-banner" : {
                    "component": "Ifuel_EmailBanner/js/banner",
                    "invalidEmail"      : "<?= $viewModel->getInvalidEmailMessage(); ?>",
                    "getSuccessMessage" : "<?= $viewModel->getSuccessMessage(); ?>",
                    "getFailMessage"    : "<?= $viewModel->getFailMessage(); ?>",
                    "getFormUrl"        : "<?= $block->getFormUrl(); ?>"
                }
            }
        }
    }
}
</script>
