<div data-bind="scope: 'timer-ui'">
    <!-- ko template:  getTemplate()--><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app" : {
                "components": {
                    "timer-ui": {
                        "component": "ModuleVendor_UiTimer/js/component",
                        "config": {
                            "template" : "ModuleVendor_UiTimer/timer-templare"
                    }
                }
            }
        }
    }
    }
</script>